version: 1.0.0.{build}

platform: x64

branches:
  only:
    - master

clone_folder: c:\gopath\src\github.com\matiasinsaurralde\appveyor-test

environment:
  GOPATH: c:\gopath
  MINGWPATH: c:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin
  MSYSPATH: c:\msys64
  MSYSBINPATH: c:\msys64\bin
  MSYSTEM: MINGW64

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=c:\msys64\usr\bin;c:\msys64\bin;C:\msys64\mingw64\bin;%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - c:\msys64\usr\bin\pacman -Syyuu --noconfirm
  - c:\msys64\usr\bin\pacman -S --noconfirm mingw64/mingw-w64-x86_64-dlfcn

build: false

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

test_script:
  - cd c:\gopath\src\github.com\matiasinsaurralde\appveyor-test
  - C:\msys64\usr\bin\bash -lc "cd ${APPVEYOR_BUILD_FOLDER} && pwd && ls && utils/ci-test.sh"

